package com.gaochlei.mulmusic.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gaochlei.mulmusic.entity.LastPlayMusic;
import com.gaochlei.mulmusic.entity.Music;
import com.gaochlei.mulmusic.entity.MusicHistory;

import com.gaochlei.mulmusic.entity.LastPlayMusicDao;
import com.gaochlei.mulmusic.entity.MusicDao;
import com.gaochlei.mulmusic.entity.MusicHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lastPlayMusicDaoConfig;
    private final DaoConfig musicDaoConfig;
    private final DaoConfig musicHistoryDaoConfig;

    private final LastPlayMusicDao lastPlayMusicDao;
    private final MusicDao musicDao;
    private final MusicHistoryDao musicHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lastPlayMusicDaoConfig = daoConfigMap.get(LastPlayMusicDao.class).clone();
        lastPlayMusicDaoConfig.initIdentityScope(type);

        musicDaoConfig = daoConfigMap.get(MusicDao.class).clone();
        musicDaoConfig.initIdentityScope(type);

        musicHistoryDaoConfig = daoConfigMap.get(MusicHistoryDao.class).clone();
        musicHistoryDaoConfig.initIdentityScope(type);

        lastPlayMusicDao = new LastPlayMusicDao(lastPlayMusicDaoConfig, this);
        musicDao = new MusicDao(musicDaoConfig, this);
        musicHistoryDao = new MusicHistoryDao(musicHistoryDaoConfig, this);

        registerDao(LastPlayMusic.class, lastPlayMusicDao);
        registerDao(Music.class, musicDao);
        registerDao(MusicHistory.class, musicHistoryDao);
    }
    
    public void clear() {
        lastPlayMusicDaoConfig.clearIdentityScope();
        musicDaoConfig.clearIdentityScope();
        musicHistoryDaoConfig.clearIdentityScope();
    }

    public LastPlayMusicDao getLastPlayMusicDao() {
        return lastPlayMusicDao;
    }

    public MusicDao getMusicDao() {
        return musicDao;
    }

    public MusicHistoryDao getMusicHistoryDao() {
        return musicHistoryDao;
    }

}
